application: bsdtdemo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  DJANGO_SETTINGS_MODULE: 'bsdtdemo.settings'

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /
  static_files: templates/index.html
  upload: templates/index\.html

- url: .*
  script: bsdtdemo.wsgi.application

libraries:
- name: django
  version: "1.4"

builtins:
- django_wsgi: on
